- lib/src/providers/home_requests_provider.dart
- lib/src/screens/home/home_no_requests_widget.dart
- lib/src/screens/home/home_requests_widget.dart
- lib/src/screens/home/home_view.dart
- lib/src/screens/home/home_view_model.dart
오류를 수정하고 요청 없을때 화면을 추가했습니다!
- 거절된 상품만 있는 경우에 api 안불러와지는 오류 수정
- 오버플로우 수정
- 검색창 ui 생성
- 카테고리 화살표 생성
- 요청 없을시 화면 추가
> Sprint3 hansle home

- lib/src/models/heart/heart_list_model.dart
- lib/src/models/product/product_list_model.dart
- lib/src/models/product/product_model.dart
- lib/src/models/product/product_service.dart
- lib/src/providers/request_exchange_provider.dart
- lib/src/screens/heart/heart_view.dart
- lib/src/screens/product_detail/product_detail.dart
- lib/src/screens/product_detail/product_detail_bottom_button.dart
- lib/src/screens/product_detail/product_detail_requests.dart
- lib/src/screens/request_exchange/request_exchange_view.dart
- lib/src/screens/request_exchange/request_exchange_view_model.dart
- lib/src/widgets/custom_appbar.dart
교환 신청하기 화면 생성했습니다
여러상품에 대해 신청하는 기능이 남아있는데, 해당 부분 구현은 조금 더 고민해봐야할 것 같아서 우선 머지 부탁드려도 될까요ㅜㅜ
그리고 만들어두신 customAppBar 사용하는중에 잘 되지 않는 부분이 있는데 확인 부탁드려요! 
leadingYn=true로 설정하고 onTap에 화살표 누르면 pop 되도록 정의했는데, 눌러도 뒤로가지지 않아서ㅜㅜ 제가 어느부분에서 잘못한지 잘 모르겠습니다 시간되실때 봐주시면 감사하겠슴니다~!
> Sprint6 minji

- lib/src/models/exchange/exchange_dto_model.dart
- lib/src/models/exchange/exchange_service.dart
- lib/src/providers/complete_exchange_provider.dart
- lib/src/screens/complete_exchange/complete_exchange_view.dart
- lib/src/screens/complete_exchange/complete_exchange_view_model.dart
- lib/src/screens/complete_exchange/exchange_confirm_modal.dart
- lib/src/screens/my_exchange/trading_and_completed_tab_widget.dart
- lib/src/widgets/custom_appbar.dart
- lib/src/widgets/long_circled_btn.dart
- pubspec.lock
- pubspec.yaml
교환 완료하기 화면과 별점주기 모달을 구현했습니다!
AppBar 문제가 있었던 이유가 leadingWidth가 0으로 설정되어 있어서 그랬네요😭 죄송합니다ㅠ0ㅠ 해당부분 수정했습니다!
그리고 다음 이미지와 같은 버튼을 LongCircledBtn 공통 위젯으로 만들었습니다 개발하실때 쓰시면 편하실 것 같습니당!
> 교환 완료하기 화면

- lib/src/models/exchange/exchange_dto_model.dart
- lib/src/models/product/product_model.dart
- lib/src/models/request/request_dto_model.dart
- lib/src/models/request/request_model.dart
- lib/src/models/request/request_service.dart
- lib/src/screens/heart/heart_view.dart
- lib/src/screens/home/home_requests_widget.dart
- lib/src/screens/home/home_view.dart
- lib/src/screens/my_exchange/products_I_requested_widget.dart
- lib/src/screens/my_exchange/trading_and_completed_tab_widget.dart
- lib/src/screens/my_page.dart
- lib/src/screens/product_detail/product_detail_bottom_button.dart
- lib/src/utilities/enums.dart
- lib/src/widgets/custom_navigation_bar.dart
백엔드 변경사항을 적용하고 회의때 변경된 디자인으로 홈화면(검색창 제거), 네비게이션바, 마이페이지를 수정했습니다!
이상한 부분 있으면 알려주세용~~!
> 백엔드 변경사항 및 회의 결정사항 적용

- lib/src/widgets/my_exchange_card.dart
- lib/src/widgets/text_style.dart
다음 이슈에 관하여 예시 코드를 작성해보았습니다 확인하시고 어떤 의견이든 피드백 주시면 감사하겠습니당~~!
- resolve #20
> Custom Text 예시

- lib/src/models/exchange/exchange_page_model.dart
- lib/src/models/exchange/exchange_service.dart
- lib/src/models/heart/heart_list_model.dart
- lib/src/models/product/product_search_page_model.dart
- lib/src/models/product/product_service.dart
- lib/src/models/request/request_dto_model.dart
- lib/src/models/request/request_service.dart
- lib/src/providers/complete_exchange_provider.dart
- lib/src/providers/product_detail_provider.dart
- lib/src/providers/search_products_provider.dart
- lib/src/screens/create_product/create_product_view.dart
- lib/src/screens/heart/heart_view.dart
- lib/src/screens/heart/heart_view_model.dart
- lib/src/screens/my_page.dart
- lib/src/screens/product_detail/product_detail.dart
- lib/src/screens/product_detail/product_detail_acceptance.dart
- lib/src/screens/product_detail/product_detail_bottom_button.dart
- lib/src/screens/product_detail/product_detail_requests.dart
- lib/src/screens/product_detail/product_detail_view_model.dart
- lib/src/screens/request_exchange/request_exchange_view.dart
- lib/src/screens/search_products/search_products_view.dart
- lib/src/screens/search_products/search_products_view_model.dart
- lib/src/utilities/shortener.dart
- lib/src/widgets/custom_navigation_bar.dart
- lib/src/widgets/text_style.dart
상품 검색화면 우선 ui까지만 완성했습니다!
코드양이 꽤 되서 우선 한번 머지하는게 어떨까 해서 요청 드립니다!
그리고 저는 상품 등록하고 나면 좋아요 false 로 잘 나타나는데, 새로 풀 받으시고 다시 확인 부탁드려도 될까요?!
> Sprint7 minji

- lib/src/providers/search_products_provider.dart
- lib/src/screens/heart/heart_view.dart
- lib/src/screens/product_detail/product_detail.dart
- lib/src/screens/product_detail/product_detail_view_model.dart
- lib/src/screens/search_products/search_products_view.dart
- lib/src/screens/search_products/search_products_view_model.dart
상품 검색 화면까지 완성해서 pr 드립니다! 테스트해보시면서 어색한부분 있으면 말씀 부탁드립니당
개인적으로는 검색화면 넘어갔을때 너무 휑한가 싶긴 한데.. 나중에 최근검색어같은게 추가될수도 있으니 괜찮으려나요?
그리고 가격 범위 설정하는 부분에서 키보드가 올라갔을때 화면이 같이 올라갔으면 좋겠는데 생각처럼 잘 안되서ㅜㅜ 대면 회의때 그부분은 다시 여쭤보겠습니다 우선 기능은 작동하는거만 확인했어요!
> Sprint8 minji

- lib/src/models/exchange/exchange_dto_model.dart
- lib/src/navada_app.dart
- lib/src/providers/accept_request_provider.dart
- lib/src/providers/complete_exchange_provider.dart
- lib/src/providers/create_product_provider.dart
- lib/src/providers/modify_product_provider.dart
- lib/src/screens/accept_request/accept_request_view.dart
- lib/src/screens/complete_exchange/complete_exchange_view.dart
- lib/src/screens/complete_exchange/exchange_confirm_modal.dart
- lib/src/screens/create_product/create_product_view.dart
- lib/src/screens/home/home_requests_widget.dart
- lib/src/screens/modify_product/modify_product_view.dart
- lib/src/screens/modify_product/modify_product_view_model.dart
- lib/src/screens/my_exchange/my_exchanges_view.dart
- lib/src/screens/my_exchange/trading_and_completed_tab_widget.dart
- lib/src/widgets/custom_navigation_bar.dart
- lib/src/widgets/star_rating.dart
물품 수정화면을 개발하고 저번 회의사항(리프레시 적용 및 교환중&교환완료화면 수정)을 적용했습니다!
교환중&교환완료화면에 별점을 넣으려다보니 dto에 별점도 넣게 되었습니다...!
신청일자는 다음 스프린트 때 해서 머지드리도록 하겠습니다...!😭😭 이상한 부분 있음 알려주시면 감사하겠습니다!
> Sprint10 hansle modify product

- lib/src/models/api/http_client.dart
- lib/src/models/product/product_model.dart
- lib/src/models/product/product_service.dart
- lib/src/providers/create_product_provider.dart
- lib/src/providers/search_products_provider.dart
- lib/src/screens/product_detail/product_detail.dart
- lib/src/screens/search_products/search_products_view.dart
- lib/src/utilities/enums.dart
기존에 로그 확인이 줄바꿈이 안되서 나와서 보기 불편한것 같아서ㅠㅠ 화면처럼 바꿔봤어요!
이렇게하니까 로그가 너무 길어지긴 해서.. 우선 기존꺼 주석처리해두었으니 더 편하신대로 사용하시면 될 것 같습니당 우선 pr로 올리긴 할게요
> Sprint9 minji

- lib/src/models/exchange/exchange_dto_model.dart
- lib/src/models/exchange/exchange_service.dart
- lib/src/providers/exchange_history_provider.dart
- lib/src/providers/my_exchanges_exchange_provider.dart
- lib/src/screens/exchange_history/exchange_history_view.dart
- lib/src/screens/my_page.dart
- lib/src/screens/product_detail/product_detail.dart
- lib/src/widgets/star_rating.dart
- pubspec.lock
- pubspec.yaml
교환 내역 화면 pr 올립니다!
교환내역 조회 api가 바뀌어서 4번째탭(교환중인 목록)도 제가 교환중인것만 받도록 수정했는데, 혹시 이상한부분 있으면 말씀 부탁드립니다!
그리고 별점 공통화면 만들어주신게 제거에서는 제대로 동작을 안해서(3.5인 경우 뒤에 두개가 모두 반이 차더라구요) 이부분도 제가 다시 수정했는데 확인 부탁드립니당
페이징적용은 제가 나중에 다른화면들이랑 일괄로 처리할게요..!!
> Sprint11 minji : 교환 내역 화면

- lib/src/screens/exchange_history/exchange_history_view.dart
- lib/src/screens/my_exchange/exchange_tab/exchange_detail/exchange_confirm_modal.dart
- lib/src/screens/my_exchange/exchange_tab/exchange_detail/exchange_detail_view.dart
- lib/src/screens/my_exchange/exchange_tab/exchange_detail/exchange_detail_view_model.dart
- lib/src/screens/my_exchange/exchange_tab/exchange_tab.dart
- lib/src/screens/my_exchange/my_exchanges_view.dart
- lib/src/screens/my_exchange/request_tab/products_I_requested_tab.dart
- lib/src/screens/my_exchange/request_tab/request_detail/request_detail_view.dart
- lib/src/widgets/text_style.dart
신청 거절 상세화면입니다! 교환탭쪽 폴더구조가 넘 복잡해서 수정해보았습니다
> 신청, 거절 상세화면 

- lib/src/models/user/user_provider.dart
- lib/src/navada_app.dart
- lib/src/providers/create_product_provider.dart
- lib/src/providers/heart_provider.dart
- lib/src/providers/modify_product_provider.dart
- lib/src/providers/my_exchanges_exchange_provider.dart
- lib/src/providers/my_exchanges_request_provider.dart
- lib/src/providers/my_products_provider.dart
- lib/src/providers/product_detail_provider.dart
- lib/src/providers/products_by_category_provider.dart
- lib/src/providers/request_exchange_provider.dart
- lib/src/providers/search_products_provider.dart
- lib/src/screens/product_detail/product_detail.dart
- lib/src/screens/tab1_home/home/home_requests_widget.dart
- lib/src/screens/tab1_home/home/home_view.dart
- lib/src/screens/tab4_exchange/my_exchange/exchange_tab/exchange_detail/exchange_confirm_modal.dart
- lib/src/screens/tab4_exchange/my_exchange/exchange_tab/exchange_detail/exchange_detail_view.dart
- lib/src/screens/tab4_exchange/my_exchange/exchange_tab/exchange_tab.dart
- lib/src/screens/tab4_exchange/my_exchange/my_exchanges_view.dart
- lib/src/screens/tab4_exchange/my_exchange/request_tab/products_I_requested_tab.dart
- lib/src/screens/tab5_mypage/account_management/setting_user_info/modify_user_info_view.dart
- lib/src/screens/tab5_mypage/account_management/setting_user_info/setting_user_info_view.dart
- lib/src/screens/tab5_mypage/exchange_history/exchange_history_view.dart
- lib/src/screens/tab5_mypage/my_page.dart
- lib/src/widgets/custom_navigation_bar.dart
user provider 관련 수정사항을 적용했습니다! 급하게 하느라 이상한 부분있으면 알려주세요! 
#48 관련
> user provider 변경

- android/app/google-services.json
- lib/src/models/product/product_model.dart
- lib/src/models/product/product_service.dart
- lib/src/models/user/user_provider.dart
- lib/src/providers/product_detail_provider.dart
- lib/src/screens/product_detail/modify_product/modify_product_view.dart
- lib/src/screens/product_detail/product_detail.dart
- lib/src/screens/product_detail/product_detail_request_modal.dart
- lib/src/screens/product_detail/product_detail_view_model.dart
- lib/src/screens/product_detail/request_exchange/request_exchange_view.dart
- lib/src/screens/tab1_home/products_by_category/products_by_category_view.dart
- lib/src/screens/tab2_products/search_products/search_products_view.dart
- lib/src/screens/tab3_create/create_product/create_product_view.dart
- lib/src/screens/tab5_mypage/heart/heart_view.dart
- lib/src/screens/tab5_mypage/my_products/my_products_view.dart
상품상세 관련 에러 없는 버전 먼저 올려야 테스트할때 편하실 것 같아서
ProductDetailDto 만든 후에 관련코드 수정했습니다!
우선 먼저 머지 해주시면 나머지 작업들은 이어서 해서 또 pr 올리겠습니당 (백앤드랑 같이 머지부탁드려요!)
> Sprint14 minji

- lib/src/models/user/user_provider.dart
- lib/src/models/user/user_service.dart
- lib/src/screens/signin/signup.dart
- lib/src/screens/tab5_mypage/my_page.dart
회원가입 창을 수정하고 회원 탈퇴 api를 연동했습니다. 이상한 부분 있으면 알려주심 감사하겠습니다! 백엔드에 관련 pr 올려놓았습니당
> 회원가입 창 수정, 회원탈퇴 api 연동

- lib/src/providers/modify_product_provider.dart
- lib/src/screens/product_detail/modify_product/modify_product_view.dart
- lib/src/screens/product_detail/modify_product/modify_product_view_model.dart
이슈 올려주신 물품 수정 api 연동 오류부분을 수정하였습니다! 늦게 pr 드려 죄송합니다! ㅠㅠ
- resolve #45
> 물품 수정 api 연동 오류 수정

- lib/src/models/api/http_client.dart
- lib/src/models/exchange/exchange_service.dart
- lib/src/models/product/product_service.dart
- lib/src/models/request/request_service.dart
- lib/src/models/user/user_provider.dart
- lib/src/models/user/user_service.dart
- lib/src/providers/signin_provider.dart
- lib/src/screens/signin/signin.dart
- lib/src/screens/signin/signup.dart
서버에서 발급한 Access Token을 받아 저장하고 요청 헤더에 넣는 작업을 수행했습니다. 백엔드와 같이 머지해주시면 감사하겠습니다! 이상한 부분있음 알려주세요~
> Access Token 적용

- lib/src/models/faq/faq_service.dart
- lib/src/models/heart/heart_service.dart
- lib/src/models/notification/notification_list_model.dart
- lib/src/models/notification/notification_service.dart
- lib/src/models/user/user_model.dart
- lib/src/providers/notification_provider.dart
- lib/src/screens/product_detail/product_detail.dart
- lib/src/screens/tab1_home/home/home_view.dart
- lib/src/screens/tab1_home/notification/notification_view.dart
- lib/src/screens/tab5_mypage/account_management/app_info/app_info_view.dart
- lib/src/utilities/enums.dart
말씀해주신대로 상품 상세화면 스크롤 되도록 수정하고 알림기능 화면 개발했습니다!
알림 여부를 홈에서 확인하는 부분은 회의해본 후에 작성 해야할 것 같습니당! 시간 되신다면 issue에 써둔 부분 확인 부탁드립니다:D
> Sprint15 minji

- lib/main.dart
- lib/src/models/api/http_client.dart
- lib/src/models/api/token/token_dto.dart
- lib/src/models/user/user_provider.dart
- lib/src/models/user/user_service.dart
- lib/src/navada_app.dart
- lib/src/providers/signin_provider.dart
- lib/src/screens/signin/signin.dart
- lib/src/screens/signin/signup.dart
- lib/src/screens/tab5_mypage/my_page.dart
다음 부분을 진행했는데 이상한 거 있으면 알려주세용!! 
- Access Token 만료시 Refresh Token을 가지고 새로운 Access Token 받아오기
- Refresh Token 만료 예외 발생시 로그인 페이지로 이동
- 백엔드 로그아웃 api 요청
- 닉네임 중복체크
- 회원가입 로직 수정(백엔드로 이메일이 아닌 소셜 토큰 보냄)
- 소셜 로그아웃 및 탈퇴 처리
> 리프레시 토큰 적용, 닉네임 중복체크, 회원가입 로직 수정, 소셜 로그아웃 및 탈퇴 처리

- lib/src/models/product/product_model.dart
- lib/src/models/product/product_service.dart
- lib/src/providers/create_product_provider.dart
- lib/src/providers/modify_product_provider.dart
- lib/src/screens/product_detail/modify_product/modify_product_view.dart
- lib/src/screens/product_detail/modify_product/modify_product_view_model.dart
- lib/src/screens/tab3_create/create_product/create_product_view.dart
- lib/src/screens/tab4_exchange/my_exchange/request_tab/products_I_requested_tab.dart
- pubspec.lock
상품 이미지 수정 부분 (모바일) 작업 했습니다!
여러 방식으로 테스트 해보긴 했는데 혹시 잘 작동되지 않는 부분 있으면 말씀해주세요!
> Sprint18 minji

- lib/src/models/user/user_provider.dart
- lib/src/navada_app.dart
- lib/src/providers/signin_provider.dart
- lib/src/screens/tab1_home/home/home_requests_widget.dart
- lib/src/screens/tab1_home/home/home_view.dart
- lib/src/screens/tab5_mypage/my_page.dart
핸드폰번호 변경 오류 수정, 회원탈퇴시 앱 유저 정보 초기화 진행했습니다.
- resolve #64 
- resolve #67 
이상한 부분있으면 알려주시면 감사하겠습니다!! 백엔드도 pr 올려놓았습니다!!
> 핸드폰번호 변경 오류 수정, 회원탈퇴시 앱 유저 정보 초기화

- lib/src/screens/tab1_home/accept_request/accept_request_view.dart
- lib/src/screens/tab1_home/home/home_requests_widget.dart
- lib/src/utilities/gcs_image.dart
이미지 반영 안된 화면들이 있어서 반영하고, 
우선 이미지 지정 안한경우에는 navada 로고 보여지도록 설정해두었습니다!!
테스트하실때 필요할것같아 우선 pr 드립니다
> 이미지 반영 및 기본이미지 로고로 임시설정
